### ISSUE TITLE
Scrolling screen

### ISSUE THREAD

**Issue by Eddie-Moreno** [Big3D/sonic-pie-project#4]
Description:

Scrolling screen

Tasks:

- Add background image to play scene
- Screen moves when moving right 
- Imagine the screen in thirds, when you move to the right third the screen begins scrolling ( ||stay| stay| move|| )

**Comment by gabymoreno9** [comment]
@Eddie-Moreno hiiii can u tell me where the background image is? is it in the clickup

**Comment by gabymoreno9** [comment]
note to me: image folder -> background
